#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 31 15:44:27 IST 2020
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 9ca553e52f7d4413a0c02a763594b347 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot test_Risc_16_bit_behav xil_defaultlib.test_Risc_16_bit xil_defaultlib.glbl -log elaborate.log"
xelab -wto 9ca553e52f7d4413a0c02a763594b347 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip --snapshot test_Risc_16_bit_behav xil_defaultlib.test_Risc_16_bit xil_defaultlib.glbl -log elaborate.log

